version: "3.7"
services:
  app:
    image: flask
    build: .
    ports:
      - target: 5000
        published: 80
    depends_on:
      - mysql
  mysql:
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=blog
